export * from "./auth";
export * from "./api";
export * from "./staff";
export * from "./finance";

// Re-export school module types explicitly to avoid duplicate symbol
// (PaginatedResponse is already exported from ./api)
export type {
	Quarter,
	AcademicYear,
	Class,
	ClassStudent,
	Subject,
	ClassSubject,
	RoomType,
	Building,
	Room,
	EquipmentItem,
	EmploymentType,
	StaffStatus,
	TransactionType,
	PaymentMethod,
	SalaryStatus,
	StaffRole,
	StaffProfile,
	BalanceTransaction,
	SalaryPayment,
	UserInfo,
	StaffRoleInfo,
	BalanceSummary,
	CheckStaffUserResponse,
	StaffStatisticsResponse,
	CreateStaffRoleRequest,
	CreateStaffProfileRequest,
	EnhancedCreateStaffRequest,
	CreateTransactionRequest,
	CreateSalaryPaymentRequest,
	TeacherClass,
	TeacherSubject,
	TeacherStudent,
	StudentClassSubject,
	StudentClass,
	StudentSubject,
	Student,
	StudentProfileSummary,
	StudentPhoneCheckBranchData,
	StudentPhoneCheckResponse,
	StudentRelative,
	RelationshipType,
	CreateAcademicYearRequest,
	CreateQuarterRequest,
	CreateClassRequest,
	AddStudentToClassRequest,
	CreateSubjectRequest,
	AddSubjectToClassRequest,
	CreateBuildingRequest,
	CreateRoomRequest,
	CreateStudentRequest,
	CreateStudentRelativeRequest,
} from "./school";
